姓名：申尚东

学号：2016011378

学院：软件学院

专业：软件工程

实训作业一：Spectral Schoolwork

In [1]:
#导入必要的模块
import numpy as np
import scipy.io as sio

In [2]:
#导入需要的数据集
load_data1 = sio.loadmat('F:/Iris/nine_train/nine_train/data2_train.mat')
load_data2 = sio.loadmat('F:/Iris/nine_train/nine_train/data3_train.mat')
load_data3 = sio.loadmat('F:/Iris/nine_train/nine_train/data5_train.mat')
load_data4 = sio.loadmat('F:/Iris/nine_train/nine_train/data6_train.mat')
load_data5 = sio.loadmat('F:/Iris/nine_train/nine_train/data8_train.mat')
load_data6 = sio.loadmat('F:/Iris/nine_train/nine_train/data10_train.mat')
load_data7 = sio.loadmat('F:/Iris/nine_train/nine_train/data11_train.mat')
load_data8 = sio.loadmat('F:/Iris/nine_train/nine_train/data12_train.mat')
load_data9 = sio.loadmat('F:/Iris/nine_train/nine_train/data14_train.mat')
test_data = sio.loadmat('F:/Iris/nine_train/data_test_final.mat')

In [3]:
#输出导入文件的有用数据部分以及每个矩阵的大小
data1 =load_data1['data2_train']
data2 =load_data2['data3_train']
data3 =load_data3['data5_train']
data4 =load_data4['data6_train']
data5 =load_data5['data8_train']
data6 =load_data6['data10_train']
data7 =load_data7['data11_train']
data8 =load_data8['data12_train']
data9 =load_data9['data14_train']
test = test_data['data_test_final']
print('data1:',data1.shape)
print('data2:',data2.shape)
print('data3:',data3.shape)
print('data4:',data4.shape)
print('data5:',data5.shape)
print('data6:',data6.shape)
print('data7:',data7.shape)
print('data8:',data8.shape)
print('data9:',data9.shape)
print('test:',test.shape)
print(data1)
print(data2)
print(data3)
print(data4)
print(data5)
print(data6)
print(data7)
print(data8)
print(data9)
print(test)

data1: (1071, 200)
data2: (622, 200)
data3: (362, 200)
data4: (547, 200)
data5: (358, 200)
data6: (729, 200)
data7: (1841, 200)
data8: (445, 200)
data9: (949, 200)
test: (2310, 200)
[[3688 4381 4594 ... 1064 1034 1010]
 [2579 4137 4412 ... 1051 1043 1005]
 [2581 4264 4328 ... 1054 1022 1009]
 ...
 [3186 4114 4213 ... 1045 1015 1009]
 [2586 4114 4226 ... 1023 1018 1014]
 [3189 4118 4492 ... 1034 1014 1009]]
[[3164 4384 4427 ... 1054 1025 1024]
 [3674 4257 4600 ... 1055 1029 1011]
 [2732 4137 4507 ... 1055 1030 1015]
 ...
 [3322 3990 4560 ... 1046 1015 1013]
 [2727 4110 4378 ... 1041 1019 1018]
 [3666 3994 4294 ... 1049 1010 1014]]
[[3183 3740 3851 ... 1006 1008 1000]
 [2585 3743 4105 ... 1015 1009 1003]
 [2583 3860 3847 ... 1007 1009 1000]
 ...
 [2986 3726 4013 ... 1022 1014 1004]
 [3322 3850 3924 ... 1017 1009 1004]
 [2981 3850 3936 ... 1012 1005 1004]]
[[3024 3861 3942 ... 1002 1009 1013]
 [3032 3869 4022 ... 1015 1009 1000]
 [2771 4105 3857 ... 1025 1009 1000]
 ...
 [3669 3979 4020 .

In [4]:
#合并9个数据集，按照从小到大，每个文件的数据对应的标签设为从1到9
data = np.vstack((data1,data2,data3,data4,data5,data6,data7,data8,data9))
label = [1,2,3,4,5,6,7,8,9]
repeat = [len(data1),len(data2),len(data3),len(data4),len(data5),len(data6),len(data7),len(data8),len(data9)]
label_data = np.repeat(label,repeat)

In [5]:
len(data)

6924

In [6]:
len(label_data)

6924

In [27]:
#切分训练集，百分之八十五训练，百分之十五测试
from sklearn.cross_validation import train_test_split
trainx,testx,trainy,testy = train_test_split(data,label_data,train_size=0.85,random_state=5)

In [28]:
#使用随机森林训练模型，得出测试集正确率为88.45%
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=10,random_state=33)
clf = clf.fit(trainx,trainy)
print(clf.score(trainx,trainy))
print(clf.score(testx,testy))

0.9971112999150382
0.8845043310875842


In [45]:
#用已经训练好的模型训练测试集
y_pre=clf.predict(test)
print(y_pre)

[8 3 2 ... 9 2 4]


In [46]:
#字典函数，把1-9换成对应的标签
def transform(argument):
    switcher = {
        1:2,
        2:3,
        3:5,
        4:6,
        5:8,
        6:10,
        7:11,
        8:12,
        9:14,
    }
    return switcher.get(argument, "nothing")

In [47]:
#转换对应的标签
for i in range(len(y_pre)):
    y_pre[i] = transform(y_pre[i])
print(y_pre)

[12  5  3 ... 14  3  6]


In [49]:
#保存标签到csv文件中
import pandas as pd
data_ = pd.DataFrame(y_pre)
data_.to_csv('test_label')